// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnxmopjrwweargsjiaxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdueG1vcGpyd3dlYXJnc2ppYXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzY2NjYsImV4cCI6MjA2MTExMjY2Nn0.Ogao49LMPBfgMyEVW0e5yZC_w6GtTi0Se1djhdWYifQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);